workflows:
  android-build:
    name: بناء Android
    max_build_duration: 60
    trigger:
      branches:
        include:
          - main
    android:
      gradle:
        gradle_version: 6.7.1
        task: assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
