workflows:
  android-build:
    name: "بناء Android"
    max_build_duration: 60
    steps:
      - name: "التثبيت"
        run: |
          flutter pub get
      - name: "بناء Android"
        run: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
