workflows:
  android-build:
    name: "بناء Android"
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: تثبيت الحزم
        script: |
          flutter pub get
      - name: بناء التطبيق لنظام Android
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
